services:
  app-authorizer:
    container_name: app-authorizer
    build:
      context: ../../app/authorizer                     # ✅ set context to where Cargo.toml is
      dockerfile: Authorizer.dev.dockerfile             # ✅ no leading ./ or ../ needed, it's relative to `context`
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../../app/authorizer:/app                       # ✅ mount source correctly
      - /app/target                              # ✅ avoid using host target dir
    networks:
      - fi-network

  app-emailer:
    container_name: app-emailer
    build:
      context: ../../app/emailer                     # ✅ set context to where Cargo.toml is
      dockerfile: Emailer.dev.dockerfile             # ✅ no leading ./ or ../ needed, it's relative to `context`
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ../../app/emailer:/app                       # ✅ mount source correctly
      - /app/target                                   # ✅ avoid using host target dir
    networks:
      - fi-network

  mailhog:
    container_name: mailhog
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - fi-network

networks:
  fi-network:
    driver: bridge




#####################################################

#services:
#  #  fe:
#  #    container_name: fe
#  #    build:
#  #      context: ../fe
#  #      dockerfile: Dockerfile
#  #    ports:
#  #      - "3000:3000"
#  #    volumes:
#  #      - ./../fe:/app
#  #      - /app/node_modules
#  #      - /app/.next
#  #    environment:
#  #      - NODE_ENV=development
#  #    command: npm run dev
#  #    networks:
#  #      - fi-network
#
#  fi-api:
#    container_name: fi-api
#    build:
#      context: ..
#      dockerfile: ./../app/api/Api.dev.dockerfile
#    restart: always
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./../app/api:/app/api
#      - /app/api/target  # Avoid using cached target from host
#    #    depends_on:
#    #      fi-api-db:
#    #        condition: service_healthy
#    #      mailhog:
#    #        condition: service_started
#    networks:
#      - fi-network
#
##  fi-api-db:
##    container_name: fi-api-db
##    image: postgres:17.4
##    restart: always
##    environment:
##      POSTGRES_DB: fiapi
##      POSTGRES_USER: root
##      POSTGRES_PASSWORD: root
##    volumes:
##      - .dbdata/postgres/:/var/lib/postgresql/data
##    healthcheck:
##      test: ["CMD-SHELL", "pg_isready -U root"]
##      interval: 5s
##      timeout: 5s
##      retries: 3
##    ports:
##      - "5432:5432"
##    networks:
##      - fi-network
##
##  mailhog:
##    container_name: mailhog:1.0.1
##    image: "mailhog/mailhog:latest"
##    ports:
##      - "1025:1025"
##      - "8025:8025"
##    networks:
##      - fi-network
#
#networks:
#  fi-network:
#    driver: bridge
