services:
  fe-authorizer:
    container_name: fe
    build:
      context: ../../frontend/authorizer
      dockerfile: Authorizer.fe.dev.dockerfile
    ports:
      - "5001:3000"
    volumes:
      - ../../frontend/authorizer:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - fi-authorizer-fe-net

networks:
  fi-authorizer-fe-net:
    driver: bridge



