services:

  # Emailer: App
  app-emailer:
    container_name: app-emailer
    build:
      context: ../../app/emailer
      dockerfile: Emailer.dev.dockerfile
    restart: always
    depends_on:
      db-app-emailer:
        condition: service_started
    ports:
      - "8002:8000"
    volumes:
      - ../../app/emailer/src:/app/src
      - ../../app/emailer/migration:/app/migration
      - ../../app/emailer/tests:/app/tests
      - ../../app/emailer/Cargo.toml:/app/Cargo.toml
      - ../../app/emailer/Cargo.lock:/app/Cargo.lock
      - /app/target
    networks:
      - fi-emailer-net

  # Emailer: DB
  db-app-emailer:
    container_name: db-app-emailer
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: emailer
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata/postgres/dev/emailer/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fi-emailer-net

networks:
  fi-emailer-net:
    driver: bridge
