services:

  #  Solana: Tx: App
  dapp-solana-tx:
    container_name: dapp-solana-tx
    build:
      context: ../../dapp/solana/tx
      dockerfile: Tx.dev.dockerfile
    restart: always
    depends_on:
      db-dapp-solana-tx:
        condition: service_started
    ports:
      - "8004:8002"
    volumes:
      - ../../dapp/solana/tx/src:/app/src
      - ../../dapp/solana/tx/migration:/app/migration
      - ../../dapp/solana/tx/tests:/app/tests
      - ../../dapp/solana/tx/Cargo.toml:/app/Cargo.toml
      - ../../dapp/solana/tx/Cargo.lock:/app/Cargo.lock
      - /app/target
    networks:
      - fi-solana-tx-net

  #  Solana: Tx: DB
  db-dapp-solana-tx:
    container_name: db-dapp-solana-tx
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: tx
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata/postgres/dev/solana_tx/:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - fi-solana-tx-net


networks:
  fi-solana-tx-net:
    driver: bridge

